---

- name: install basic packages
  sudo: yes
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
    - build-essential
    - curl
    - git
    - iftop
    - iotop
    - python-pycurl
    - sysstat
    - zsh

- name: install oh-my-zsh
  git: repo=git@github.com:robbyrussell/oh-my-zsh.git
       accept_hostkey=true
       dest={{ oh_my_zsh_install_path }}

- name: change user preferences
  sudo: true
  user: name={{ ansible_ssh_user }} shell=/bin/zsh

- name: copy over shell profile
  copy: src=zshrc dest=~/.zshrc

- name: install rvm
  shell: curl -sSL https://get.rvm.io | bash -s stable creates=~/.rvm

- name: install ruby
  shell: >
    executable=/bin/bash
    creates=~/.rvm/rubies/{{ ruby_version }}
    source .rvm/scripts/rvm && rvm install {{ ruby_version }}
