export ZSH=~/.oh-my-zsh
export ZSH_THEME="clean"

plugins=(git bundler rvm)

source $ZSH/oh-my-zsh.sh

export TERM=xterm-256color

PATH=/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/local/sbin:/usr/sbin:/sbin
PATH=$PATH:/home/vagrant/.rvm/bin

export PATH

setopt auto_pushd
setopt PUSHD_TO_HOME

cd /docker_test